import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "./context/AuthContext";
import { ChatProvider } from "./context/ChatContext";
import { UIProvider } from "./context/UIContext";


export const metadata: Metadata = {
  title: "Periskop Assignment (Shivam.strive@gmail.com)",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthProvider>
      <ChatProvider>
        <UIProvider>
          <html>
            <body>{children}</body>
          </html>
        </UIProvider>
      </ChatProvider>
    </AuthProvider>
  );
}
